language: python
python:
  - "3.6"
script:
  - bash ./test
install:
  - pip3 install -r requirements.txt
matrix:
  include:
    - name: "Linux"
      os: linux
    - name: "OSX"
      os: osx
      language: shell # 'language: python' is an error on Travis CI macOS
