#!/bin/sh

#  Copyright (c) 2019 Martin Sustrik
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom
#  the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
#  IN THE SOFTWARE.

set -ex

ROOT=$(dirname "$0")
UXY=$ROOT/uxy
TESTDATA=$ROOT/testdata

test_parser() {
  $UXY --test $1 < $TESTDATA/$2.source > $TESTDATA/$2.result
  diff $TESTDATA/$2.result $TESTDATA/$2.expected
}

# Make sure that the tools don't straight out fail.

$UXY ls testdata | $UXY align
$UXY ls testdata | $UXY to-csv | $UXY from-csv
$UXY du
$UXY -l du
$UXY ls testdata | $UXY fmt "NAME SIZE"
$UXY ls testdata | $UXY grep a
$UXY ls testdata | $UXY grep a NAME
$UXY ifconfig
$UXY -l ifconfig
echo ABC | $UXY import COL "(.*)"
$UXY ls testdata | $UXY to-json | $UXY from-json
$UXY ls testdata
$UXY -l ls testdata
$UXY lsof
$UXY -l lsof
$UXY netstat
$UXY -l netstat
$UXY ps
$UXY -l ps
$UXY top
$UXY -l top
$UXY ls testdata | $UXY trim
$UXY w
$UXY -l w


# Check the parsers against the inputs collected from different systems.
test_parser ls ls-short-linux-1
